<a href="https://colab.research.google.com/github/inekeyuliam/data-science-classification-python/blob/master/DecisionTree_drug.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier

In [ ]:
df = pd.read_csv('drug200.csv')
df

Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [ ]:
df.shape

(200, 6)

In [ ]:
X = np.asarray(df[['Age','Sex','BP','Cholesterol','Na_to_K']])
X[0:5]

array([[23, 'F', 'HIGH', 'HIGH', 25.355],
       [47, 'M', 'LOW', 'HIGH', 13.093],
       [47, 'M', 'LOW', 'HIGH', 10.113999999999999],
       [28, 'F', 'NORMAL', 'HIGH', 7.797999999999999],
       [61, 'F', 'LOW', 'HIGH', 18.043]], dtype=object)

In [ ]:
from sklearn import preprocessing
le_sex = preprocessing.LabelEncoder()
le_sex.fit(['F','M'])
X[:,1] = le_sex.transform(X[:,1])

le_bp = preprocessing.LabelEncoder()
le_bp.fit(['HIGH','LOW','NORMAL'])
X[:,2] = le_bp.transform(X[:,2])

le_ch = preprocessing.LabelEncoder()
le_ch.fit(['HIGH','NORMAL'])
X[:,3] = le_ch.transform(X[:,3])

X[0:5]

array([[23, 0, 0, 0, 25.355],
       [47, 1, 1, 0, 13.093],
       [47, 1, 1, 0, 10.113999999999999],
       [28, 0, 2, 0, 7.797999999999999],
       [61, 0, 1, 0, 18.043]], dtype=object)

In [ ]:
y = df['Drug']
y[0:5]

0    DrugY
1    drugC
2    drugC
3    drugX
4    DrugY
Name: Drug, dtype: object

In [ ]:
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.29159102, -1.040833  , -1.11016894, -0.97043679,  1.28652212],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.4151454 ],
       [ 0.16269866,  0.96076892,  0.10979693, -0.97043679, -0.82855818],
       [-0.988614  , -1.040833  ,  1.32976279, -0.97043679, -1.14996267],
       [ 1.0110343 , -1.040833  ,  0.10979693, -0.97043679,  0.27179427]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print("train set: ", X_train.shape, y_train.shape)
print("test set: ", X_test.shape, y_test.shape)

train set:  (160, 5) (160,)
test set:  (40, 5) (40,)


In [ ]:
drugtree = DecisionTreeClassifier(criterion="entropy", max_depth=4)
drugtree

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
drugtree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
predtree = drugtree.predict(X_test)
print("pred : ", predtree)
print("ytest : ", y_test)

pred :  ['DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugC' 'drugX' 'DrugY' 'DrugY' 'DrugY'
 'drugA' 'drugA' 'drugX' 'drugA' 'DrugY' 'DrugY' 'DrugY' 'DrugY' 'drugX'
 'drugA' 'drugC' 'drugX' 'drugC' 'drugA' 'drugX' 'drugC' 'drugB' 'drugX'
 'DrugY' 'drugX' 'DrugY' 'drugB' 'drugC' 'drugX' 'drugX' 'DrugY' 'DrugY'
 'drugA' 'drugA' 'drugX' 'DrugY']
ytest :  11     DrugY
99     DrugY
128    DrugY
175    DrugY
1      drugC
111    drugX
90     DrugY
177    DrugY
88     DrugY
187    drugA
61     drugA
199    drugX
191    drugA
123    DrugY
184    DrugY
188    DrugY
33     DrugY
171    drugX
138    drugB
84     drugC
81     drugX
102    drugC
147    drugA
34     drugX
47     drugC
124    drugB
112    drugX
6      DrugY
14     drugX
190    DrugY
80     drugB
18     drugC
167    drugX
45     drugX
153    drugX
119    DrugY
100    drugA
83     drugA
181    drugX
71     DrugY
Name: Drug, dtype: object


In [ ]:
from sklearn import metrics
import matplotlib.pyplot as plt
print("Decision tree accuracy : ", metrics.accuracy_score(y_test,predtree))

Decision tree accuracy :  0.95
