<a href="https://colab.research.google.com/github/inekeyuliam/data-science-classification-python/blob/master/DecisionTree_glass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pylab as pl

In [ ]:
df = pd.read_csv('glass.csv')
df

RI     Na    Mg    Al     Si     K    Ca    Ba   Fe  Type
0    1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.00  0.0     1
1    1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.00  0.0     1
2    1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.00  0.0     1
3    1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.00  0.0     1
4    1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.00  0.0     1
..       ...    ...   ...   ...    ...   ...   ...   ...  ...   ...
209  1.51623  14.14  0.00  2.88  72.61  0.08  9.18  1.06  0.0     7
210  1.51685  14.92  0.00  1.99  73.06  0.00  8.40  1.59  0.0     7
211  1.52065  14.36  0.00  2.02  73.42  0.00  8.44  1.64  0.0     7
212  1.51651  14.38  0.00  1.94  73.61  0.00  8.48  1.57  0.0     7
213  1.51711  14.23  0.00  2.08  73.36  0.00  8.62  1.67  0.0     7

[214 rows x 10 columns]

In [ ]:
X = np.asarray(df[['RI','Na','Mg','Al','Si','K','Ca','Ba','Fe']])
X[0:5]

array([[1.52101e+00, 1.36400e+01, 4.49000e+00, 1.10000e+00, 7.17800e+01,
        6.00000e-02, 8.75000e+00, 0.00000e+00, 0.00000e+00],
       [1.51761e+00, 1.38900e+01, 3.60000e+00, 1.36000e+00, 7.27300e+01,
        4.80000e-01, 7.83000e+00, 0.00000e+00, 0.00000e+00],
       [1.51618e+00, 1.35300e+01, 3.55000e+00, 1.54000e+00, 7.29900e+01,
        3.90000e-01, 7.78000e+00, 0.00000e+00, 0.00000e+00],
       [1.51766e+00, 1.32100e+01, 3.69000e+00, 1.29000e+00, 7.26100e+01,
        5.70000e-01, 8.22000e+00, 0.00000e+00, 0.00000e+00],
       [1.51742e+00, 1.32700e+01, 3.62000e+00, 1.24000e+00, 7.30800e+01,
        5.50000e-01, 8.07000e+00, 0.00000e+00, 0.00000e+00]])

In [ ]:
y = np.asarray(df['Type'])
y[0:5]

array([1, 1, 1, 1, 1])

In [ ]:
from sklearn import preprocessing

X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.87286765,  0.28495326,  1.25463857, -0.69244192, -1.12708201,
        -0.67170546, -0.14576634, -0.35287683, -0.5864509 ],
       [-0.24933347,  0.59181718,  0.63616803, -0.17046023,  0.10231907,
        -0.02621325, -0.79373376, -0.35287683, -0.5864509 ],
       [-0.72131806,  0.14993314,  0.60142249,  0.19091171,  0.43878673,
        -0.16453301, -0.82894938, -0.35287683, -0.5864509 ],
       [-0.23283051, -0.24285268,  0.69870999, -0.31099376, -0.0529737 ,
         0.11210651, -0.51905192, -0.35287683, -0.5864509 ],
       [-0.31204471, -0.16920534,  0.65006624, -0.41137486,  0.55525631,
         0.08136879, -0.62469878, -0.35287683, -0.5864509 ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train, y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print("train set : ", X_train.shape, y_train.shape)
print("test set : ", X_test.shape, y_test.shape)

train set :  (171, 9) (171,)
test set :  (43, 9) (43,)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
glasstree = DecisionTreeClassifier(criterion='entropy', max_depth=4)
glasstree

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
glasstree.fit(X_train,y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=4, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [ ]:
predicttree = glasstree.predict(X_test)
print("predict : ", predicttree)
print("ytest : " , y_test)

predict :  [1 7 2 1 1 2 5 2 2 2 2 1 1 6 1 1 2 7 7 1 1 1 7 2 2 7 1 1 7 2 2 7 1 1 1 2 1
 1 1 2 5 7 2]
ytest :  [1 7 2 1 2 1 5 2 2 2 5 1 1 6 1 2 2 7 7 1 1 2 7 2 6 7 1 1 7 2 2 7 1 1 2 2 1
 1 2 2 2 5 2]


In [ ]:
from sklearn import metrics

print("decision tree accuracy : ", metrics.accuracy_score(y_test,predicttree))

decision tree accuracy :  0.7674418604651163


In [50]:
from sklearn.metrics import classification_report
print(classification_report(y_test,predicttree))

              precision    recall  f1-score   support

           1       0.72      0.93      0.81        14
           2       0.79      0.65      0.71        17
           5       0.50      0.33      0.40         3
           6       1.00      0.50      0.67         2
           7       0.88      1.00      0.93         7

    accuracy                           0.77        43
   macro avg       0.78      0.68      0.70        43
weighted avg       0.77      0.77      0.76        43

