<a href="https://colab.research.google.com/github/inekeyuliam/data-science-classification-python/blob/master/Logistic_breast_cancer_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import pylab as pl
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('Breast_cancer_data.csv')
df

mean_radius  mean_texture  ...  mean_smoothness  diagnosis
0          17.99         10.38  ...          0.11840          0
1          20.57         17.77  ...          0.08474          0
2          19.69         21.25  ...          0.10960          0
3          11.42         20.38  ...          0.14250          0
4          20.29         14.34  ...          0.10030          0
..           ...           ...  ...              ...        ...
564        21.56         22.39  ...          0.11100          0
565        20.13         28.25  ...          0.09780          0
566        16.60         28.08  ...          0.08455          0
567        20.60         29.33  ...          0.11780          0
568         7.76         24.54  ...          0.05263          1

[569 rows x 6 columns]

In [ ]:
missingvalues = df.isnull()
#missingvalues.head()
for column in missingvalues:
  print(column)
  print(missingvalues[column].value_counts())
  print("")

mean_radius
False    569
Name: mean_radius, dtype: int64

mean_texture
False    569
Name: mean_texture, dtype: int64

mean_perimeter
False    569
Name: mean_perimeter, dtype: int64

mean_area
False    569
Name: mean_area, dtype: int64

mean_smoothness
False    569
Name: mean_smoothness, dtype: int64

diagnosis
False    569
Name: diagnosis, dtype: int64



In [ ]:
X = np.asarray(df[['mean_radius','mean_texture','mean_perimeter','mean_area','mean_smoothness']])
X[0:5]

In [ ]:
y = np.asarray(df['diagnosis'])
y[0:5]

array([0, 0, 0, 0, 0])

In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 1.09706398, -2.07333501,  1.26993369,  0.9843749 ,  1.56846633],
       [ 1.82982061, -0.35363241,  1.68595471,  1.90870825, -0.82696245],
       [ 1.57988811,  0.45618695,  1.56650313,  1.55888363,  0.94221044],
       [-0.76890929,  0.25373211, -0.59268717, -0.76446379,  3.28355348],
       [ 1.75029663, -1.15181643,  1.77657315,  1.82622928,  0.28037183]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print("train set: ", X_train, y_train)
print("test set: ", X_test, y_test)

train set:  [[-0.8711544  -1.00753827 -0.84353549 -0.79916184  0.49386816]
 [ 0.23366083 -0.40017375  0.20104799  0.06601417  1.44748508]
 [ 0.20809955 -0.54677898  0.1203152   0.05350012 -0.50671796]
 ...
 [-0.03047238 -0.84464357 -0.09799286 -0.13762358 -1.18848289]
 [-0.98476008 -0.963324   -1.00829629 -0.86827354 -0.60065634]
 [ 2.87499285  0.2118449   3.05758838  3.14589289  3.44011745]] [1 0 1 0 0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 1 0 1 1 1
 1 1 1 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 0 1 0 1 1 1 0 1
 1 1 0 0 1 1 1 0 0 1 1 0 1 1 0 1 0 1 0 1 1 1 1 1 0 1 1 1 0 1 1 0 1 0 1 0 1
 0 1 1 0 1 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 1 1 0 1 0 0 1 0 1 0 0 0 1 1 0 1
 1 1 0 1 0 1 1 1 0 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 0 1 1 0 1 1 1 1 1 0 0 1 0
 1 1 1 0 1 0 1 0 1 1 1 1 0 1 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 0 1
 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 1 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0
 0 1 0 1 1 1 0 1 0 0 1 1 1 0 1 0 1 0 0 1 0 1 1 1 0 1 1 1 0 1 1 1 0 0 0 1 0
 1 1

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=0.01, solver="liblinear").fit(X_train,y_train)
lr

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
yhat = lr.predict(X_test)
yhat

array([1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1])

In [ ]:
yhatprob = lr.predict_proba(X_test)
yhatprob

array([[0.4174681 , 0.5825319 ],
       [0.20955647, 0.79044353],
       [0.90817443, 0.09182557],
       [0.7447701 , 0.2552299 ],
       [0.6318632 , 0.3681368 ],
       [0.56620983, 0.43379017],
       [0.12557579, 0.87442421],
       [0.21564371, 0.78435629],
       [0.48035234, 0.51964766],
       [0.12560419, 0.87439581],
       [0.83586762, 0.16413238],
       [0.42383594, 0.57616406],
       [0.36597459, 0.63402541],
       [0.19204117, 0.80795883],
       [0.25853444, 0.74146556],
       [0.19959009, 0.80040991],
       [0.16685955, 0.83314045],
       [0.26229722, 0.73770278],
       [0.23834071, 0.76165929],
       [0.34422044, 0.65577956],
       [0.21392623, 0.78607377],
       [0.42494854, 0.57505146],
       [0.57273983, 0.42726017],
       [0.20975941, 0.79024059],
       [0.17288976, 0.82711024],
       [0.70557584, 0.29442416],
       [0.213063  , 0.786937  ],
       [0.15722094, 0.84277906],
       [0.38836678, 0.61163322],
       [0.23212247, 0.76787753],
       [0.

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report,log_loss,jaccard_similarity_score
print(confusion_matrix(y_test, yhat))

[[30  4]
 [ 6 74]]


In [ ]:
jaccard_similarity_score(y_test,yhat)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.9122807017543859

In [ ]:
print(classification_report(y_test,yhat))

              precision    recall  f1-score   support

           0       0.83      0.88      0.86        34
           1       0.95      0.93      0.94        80

    accuracy                           0.91       114
   macro avg       0.89      0.90      0.90       114
weighted avg       0.91      0.91      0.91       114



In [ ]:
log_loss(y_test,yhatprob)

0.3323623658842832