<a href="https://colab.research.google.com/github/inekeyuliam/data-science-classification-python/blob/master/Logistic_health_insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import pylab as pl
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('train.csv')
df.head()

id  Gender  Age  ...  Policy_Sales_Channel  Vintage  Response
0   1    Male   44  ...                  26.0      217         1
1   2    Male   76  ...                  26.0      183         0
2   3    Male   47  ...                  26.0       27         1
3   4    Male   21  ...                 152.0      203         0
4   5  Female   29  ...                 152.0       39         0

[5 rows x 12 columns]

In [ ]:
df.dtypes
missingvalues = df.isnull()
missingvalues.head()

id  Gender    Age  ...  Policy_Sales_Channel  Vintage  Response
0  False   False  False  ...                 False    False     False
1  False   False  False  ...                 False    False     False
2  False   False  False  ...                 False    False     False
3  False   False  False  ...                 False    False     False
4  False   False  False  ...                 False    False     False

[5 rows x 12 columns]

In [ ]:
for column in missingvalues:
  print(column)
  print(missingvalues[column].value_counts())
  print("")

id
False    381109
Name: id, dtype: int64

Gender
False    381109
Name: Gender, dtype: int64

Age
False    381109
Name: Age, dtype: int64

Driving_License
False    381109
Name: Driving_License, dtype: int64

Region_Code
False    381109
Name: Region_Code, dtype: int64

Previously_Insured
False    381109
Name: Previously_Insured, dtype: int64

Vehicle_Age
False    381109
Name: Vehicle_Age, dtype: int64

Vehicle_Damage
False    381109
Name: Vehicle_Damage, dtype: int64

Annual_Premium
False    381109
Name: Annual_Premium, dtype: int64

Policy_Sales_Channel
False    381109
Name: Policy_Sales_Channel, dtype: int64

Vintage
False    381109
Name: Vintage, dtype: int64

Response
False    381109
Name: Response, dtype: int64



In [ ]:
df.corr()

id       Age  ...   Vintage  Response
id                    1.000000  0.001561  ... -0.000630 -0.001368
Age                   0.001561  1.000000  ... -0.001264  0.111147
Driving_License      -0.000564 -0.079782  ... -0.000848  0.010155
Region_Code          -0.000572  0.042574  ... -0.002750  0.010570
Previously_Insured    0.002457 -0.254682  ...  0.002537 -0.341170
Annual_Premium        0.003027  0.067507  ... -0.000608  0.022575
Policy_Sales_Channel -0.002837 -0.577826  ...  0.000002 -0.139042
Vintage              -0.000630 -0.001264  ...  1.000000 -0.001050
Response             -0.001368  0.111147  ... -0.001050  1.000000

[9 rows x 9 columns]

In [ ]:
i_df = df[['Age','Driving_License','Previously_Insured','Annual_Premium','Vehicle_Age','Vehicle_Damage','Vintage','Policy_Sales_Channel','Response']]
i_df

Age  Driving_License  ...  Policy_Sales_Channel  Response
0        44                1  ...                  26.0         1
1        76                1  ...                  26.0         0
2        47                1  ...                  26.0         1
3        21                1  ...                 152.0         0
4        29                1  ...                 152.0         0
...     ...              ...  ...                   ...       ...
381104   74                1  ...                  26.0         0
381105   30                1  ...                 152.0         0
381106   21                1  ...                 160.0         0
381107   68                1  ...                 124.0         0
381108   46                1  ...                  26.0         0

[381109 rows x 9 columns]

In [ ]:
i_df['Vehicle_Age'].value_counts()

1-2 Year     200316
< 1 Year     164786
> 2 Years     16007
Name: Vehicle_Age, dtype: int64

In [ ]:
X=np.asarray(df[['Age','Driving_License','Previously_Insured','Annual_Premium','Vehicle_Age','Vehicle_Damage','Vintage','Policy_Sales_Channel']])
X[0:5]

array([[44, 1, 0, 40454.0, '> 2 Years', 'Yes', 217, 26.0],
       [76, 1, 0, 33536.0, '1-2 Year', 'No', 183, 26.0],
       [47, 1, 0, 38294.0, '> 2 Years', 'Yes', 27, 26.0],
       [21, 1, 1, 28619.0, '< 1 Year', 'No', 203, 152.0],
       [29, 1, 1, 27496.0, '< 1 Year', 'No', 39, 152.0]], dtype=object)

In [ ]:
from sklearn import preprocessing

le_age = preprocessing.LabelEncoder()
le_age.fit(['1-2 Year','> 2 Years','< 1 Year'])
X[:,4]=le_age.transform(X[:,4])
le_dmg = preprocessing.LabelEncoder()
le_dmg.fit(['Yes','No'])
X[:,5]=le_dmg.transform(X[:,5])
X[0:5]

array([[44, 1, 0, 40454.0, 2, 1, 217, 26.0],
       [76, 1, 0, 33536.0, 0, 0, 183, 26.0],
       [47, 1, 0, 38294.0, 2, 1, 27, 26.0],
       [21, 1, 1, 28619.0, 1, 0, 203, 152.0],
       [29, 1, 1, 27496.0, 1, 0, 39, 152.0]], dtype=object)

In [ ]:
y = np.asarray(df['Response'])
y[0:5]

array([1, 0, 1, 0, 0])

In [ ]:
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.33377727,  0.04620794, -0.91963797,  0.57453868,  2.5681502 ,
         0.99029399,  0.74879538, -1.58723371],
       [ 2.39675074,  0.04620794, -0.91963797,  0.17263624, -0.89387314,
        -1.00980114,  0.34244286, -1.58723371],
       [ 0.52718104,  0.04620794, -0.91963797,  0.4490531 ,  2.5681502 ,
         0.99029399, -1.52199808, -1.58723371],
       [-1.14898491,  0.04620794,  1.08738442, -0.11301775,  0.83713853,
        -1.00980114,  0.58147376,  0.73732126],
       [-0.63324154,  0.04620794,  1.08738442, -0.17825864,  0.83713853,
        -1.00980114, -1.37857955,  0.73732126]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=4)
print("train set : ", X_train.shape, y_train.shape)
print("test set : ", X_test.shape, y_test.shape)

train set :  (304887, 8) (304887,)
test set :  (76222, 8) (76222,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
lr = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
lr

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
yhat = lr.predict(X_test)
yhat

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
yhatprob = lr.predict_proba(X_test)
yhatprob

array([[0.9970059 , 0.0029941 ],
       [0.71252004, 0.28747996],
       [0.74627763, 0.25372237],
       ...,
       [0.9980964 , 0.0019036 ],
       [0.99832904, 0.00167096],
       [0.96580481, 0.03419519]])

In [ ]:
from sklearn.metrics import jaccard_similarity_score,classification_report,log_loss
jaccard_similarity_score(y_test,yhat)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.8765185904332082

In [ ]:
print(classification_report(y_test,yhat))

              precision    recall  f1-score   support

           0       0.88      1.00      0.93     66810
           1       0.00      0.00      0.00      9412

    accuracy                           0.88     76222
   macro avg       0.44      0.50      0.47     76222
weighted avg       0.77      0.88      0.82     76222



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
log_loss(y_test,yhatprob)

0.2821571984094656