<a href="https://colab.research.google.com/github/inekeyuliam/data-science-classification-python/blob/master/Logistic_credit_card_approval.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt

In [ ]:

df = pd.read_csv('credit_card_approval.csv')
df


FileNotFoundError: ignored

In [ ]:
df.dtypes
missing_data = df.isnull()
missing_data.head(5)
for column in missing_data.columns.values.tolist():
    print(column)
    print (missing_data[column].value_counts())
    print("")  

ID
False    537667
Name: ID, dtype: int64

CODE_GENDER
False    537667
Name: CODE_GENDER, dtype: int64

FLAG_OWN_CAR
False    537667
Name: FLAG_OWN_CAR, dtype: int64

FLAG_OWN_REALTY
False    537667
Name: FLAG_OWN_REALTY, dtype: int64

CNT_CHILDREN
False    537667
Name: CNT_CHILDREN, dtype: int64

AMT_INCOME_TOTAL
False    537667
Name: AMT_INCOME_TOTAL, dtype: int64

NAME_EDUCATION_TYPE
False    537667
Name: NAME_EDUCATION_TYPE, dtype: int64

NAME_FAMILY_STATUS
False    537667
Name: NAME_FAMILY_STATUS, dtype: int64

NAME_HOUSING_TYPE
False    537667
Name: NAME_HOUSING_TYPE, dtype: int64

DAYS_BIRTH
False    537667
Name: DAYS_BIRTH, dtype: int64

DAYS_EMPLOYED
False    537667
Name: DAYS_EMPLOYED, dtype: int64

FLAG_MOBIL
False    537667
Name: FLAG_MOBIL, dtype: int64

FLAG_WORK_PHONE
False    537667
Name: FLAG_WORK_PHONE, dtype: int64

FLAG_PHONE
False    537667
Name: FLAG_PHONE, dtype: int64

FLAG_EMAIL
False    537667
Name: FLAG_EMAIL, dtype: int64

JOB
False    537667
Name: JOB, dtyp

In [ ]:
credit_df = df[['CODE_GENDER','FLAG_OWN_CAR','FLAG_OWN_REALTY','CNT_CHILDREN','AMT_INCOME_TOTAL','NAME_HOUSING_TYPE','DAYS_EMPLOYED','BEGIN_MONTHS','STATUS','TARGET']]
credit_df.head()



CODE_GENDER FLAG_OWN_CAR FLAG_OWN_REALTY  ... BEGIN_MONTHS  STATUS TARGET
0           F            Y               N  ...           -6       C      0
1           F            N               N  ...           -4       0      0
2           M            Y               Y  ...            0       C      0
3           F            Y               Y  ...           -3       0      0
4           M            Y               Y  ...          -29       0      0

[5 rows x 10 columns]

In [ ]:
credit_df['NAME_HOUSING_TYPE'].value_counts()
credit_df['STATUS'].value_counts()

C    226185
0    200930
X    102167
1      6423
5      1087
2       542
3       181
4       152
Name: STATUS, dtype: int64

In [ ]:
X = np.asarray(df[['CODE_GENDER','FLAG_OWN_CAR','FLAG_OWN_REALTY','CNT_CHILDREN','AMT_INCOME_TOTAL','NAME_HOUSING_TYPE','DAYS_EMPLOYED','BEGIN_MONTHS','STATUS']])
X[0:5]

array([['F', 'Y', 'N', '2+ children', 270000.0, 'With parents', -2300,
        -6, 'C'],
       ['F', 'N', 'N', 'No children', 81000.0, 'House / apartment', -377,
        -4, '0'],
       ['M', 'Y', 'Y', 'No children', 270000.0, 'House / apartment',
        -1028, 0, 'C'],
       ['F', 'Y', 'Y', '1 children', 112500.0, 'House / apartment',
        -1956, -3, '0'],
       ['M', 'Y', 'Y', '2+ children', 139500.0, 'House / apartment',
        -5578, -29, '0']], dtype=object)

In [ ]:
from sklearn import preprocessing
le_gen = preprocessing.LabelEncoder()
le_gen.fit(['F','M'])
X[:,0] = le_gen.transform(X[:,0]) 

le_car = preprocessing.LabelEncoder()
le_car.fit(['Y','N'])
X[:,1] = le_car.transform(X[:,1])

le_realty = preprocessing.LabelEncoder()
le_realty.fit(['Y','N'])
X[:,2] = le_realty.transform(X[:,2])

le_child = preprocessing.LabelEncoder()
le_child.fit(['No children','1 children','2+ children'])
X[:,3] = le_child.transform(X[:,3])

le_house = preprocessing.LabelEncoder()
le_house.fit(['House / apartment','With parents','Municipal apartment','Rented apartment','Office apartment','Co-op apartment'])
X[:,5] = le_house.transform(X[:,5])

le_stts = preprocessing.LabelEncoder()
le_stts.fit(['C','X','0','1','2','3','4','5'])
X[:,8] = le_stts.transform(X[:,8])
X[0:5]


array([[0, 1, 0, 1, 270000.0, 5, -2300, -6, 6],
       [0, 0, 0, 2, 81000.0, 1, -377, -4, 0],
       [1, 1, 1, 2, 270000.0, 1, -1028, 0, 6],
       [0, 1, 1, 0, 112500.0, 1, -1956, -3, 0],
       [1, 1, 1, 1, 139500.0, 1, -5578, -29, 0]], dtype=object)

In [ ]:
y = np.asarray(df['TARGET'])
y[0:5]

array([0, 0, 0, 0, 0])

In [ ]:
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-0.78140358,  1.15018999, -1.34070623, -0.47385931,  0.69986236,
         3.70576304,  0.19300163,  0.94781431,  0.68870638],
       [-0.78140358, -0.86942158, -1.34070623,  0.70864901, -1.11502199,
        -0.31001919,  0.99628755,  1.09028663, -1.2608458 ],
       [ 1.27974842,  1.15018999,  0.74587555,  0.70864901,  0.69986236,
        -0.31001919,  0.72434832,  1.37523128,  0.68870638],
       [-0.78140358,  1.15018999,  0.74587555, -1.65636763, -0.81254127,
        -0.31001919,  0.33669917,  1.1615228 , -1.2608458 ],
       [ 1.27974842,  1.15018999,  0.74587555, -0.47385931, -0.55327207,
        -0.31001919, -1.17630218, -0.69061743, -1.2608458 ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=4)
print("train set: ", X_train.shape, y_train.shape )
print("test set: ", X_test.shape, y_test.shape)

train set:  (430133, 9) (430133,)
test set:  (107534, 9) (107534,)


In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
lr = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
lr

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
yhat = lr.predict(X_test)
yhat

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
yhatprob = lr.predict_proba(X_test)
yhatprob

array([[0.99428715, 0.00571285],
       [0.9937109 , 0.0062891 ],
       [0.9940619 , 0.0059381 ],
       ...,
       [0.99290164, 0.00709836],
       [0.99439132, 0.00560868],
       [0.99549091, 0.00450909]])

In [ ]:
from sklearn.metrics import jaccard_similarity_score, classification_report,log_loss
jaccard_similarity_score(y_test,yhat)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.9964104376290289

In [ ]:
confusion_matrix(y_test,yhat)

In [ ]:
print (classification_report(y_test, yhat))


              precision    recall  f1-score   support

           0       1.00      1.00      1.00    107148
           1       0.00      0.00      0.00       386

    accuracy                           1.00    107534
   macro avg       0.50      0.50      0.50    107534
weighted avg       0.99      1.00      0.99    107534



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
log_loss(y_test,yhatprob)

0.02365771718370205