<a href="https://colab.research.google.com/github/inekeyuliam/data-science-classification-python/blob/master/Logistic_Diabetics_pred.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import pylab as pl
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('diabetes2.csv')
df


Pregnancies  Glucose  ...  Age  Outcome
0              6      148  ...   50        1
1              1       85  ...   31        0
2              8      183  ...   32        1
3              1       89  ...   21        0
4              0      137  ...   33        1
..           ...      ...  ...  ...      ...
763           10      101  ...   63        0
764            2      122  ...   27        0
765            5      121  ...   30        0
766            1      126  ...   47        1
767            1       93  ...   23        0

[768 rows x 9 columns]

In [ ]:
avg_insulin = df['Insulin'].astype('float').mean(axis=0)
print(avg_insulin)
df['Insulin'].replace(0,avg_insulin,inplace=True)

79.79947916666667


In [ ]:
df.head()

Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [ ]:
missingvalues = df.isnull()
for column in missingvalues:
  print(column)
  print(missingvalues[column].value_counts())
  print("")

Pregnancies
False    768
Name: Pregnancies, dtype: int64

Glucose
False    768
Name: Glucose, dtype: int64

BloodPressure
False    768
Name: BloodPressure, dtype: int64

SkinThickness
False    768
Name: SkinThickness, dtype: int64

Insulin
False    768
Name: Insulin, dtype: int64

BMI
False    768
Name: BMI, dtype: int64

DiabetesPedigreeFunction
False    768
Name: DiabetesPedigreeFunction, dtype: int64

Age
False    768
Name: Age, dtype: int64

Outcome
False    768
Name: Outcome, dtype: int64



In [ ]:
X =np.asarray(df[['Pregnancies','Glucose','BloodPressure','SkinThickness','Insulin','BMI','DiabetesPedigreeFunction','Age']])
X[0:5]

array([[6.00000000e+00, 1.48000000e+02, 7.20000000e+01, 3.50000000e+01,
        7.97994792e+01, 3.36000000e+01, 6.27000000e-01, 5.00000000e+01],
       [1.00000000e+00, 8.50000000e+01, 6.60000000e+01, 2.90000000e+01,
        7.97994792e+01, 2.66000000e+01, 3.51000000e-01, 3.10000000e+01],
       [8.00000000e+00, 1.83000000e+02, 6.40000000e+01, 0.00000000e+00,
        7.97994792e+01, 2.33000000e+01, 6.72000000e-01, 3.20000000e+01],
       [1.00000000e+00, 8.90000000e+01, 6.60000000e+01, 2.30000000e+01,
        9.40000000e+01, 2.81000000e+01, 1.67000000e-01, 2.10000000e+01],
       [0.00000000e+00, 1.37000000e+02, 4.00000000e+01, 3.50000000e+01,
        1.68000000e+02, 4.31000000e+01, 2.28800000e+00, 3.30000000e+01]])

In [ ]:
y = np.asarray(df['Outcome'])
y[0:5]

array([1, 0, 1, 0, 1])

In [ ]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[ 0.63994726,  0.84832379,  0.14964075,  0.90726993, -0.41776815,
         0.20401277,  0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575,  0.53090156, -0.41776815,
        -0.68442195, -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, -1.28821221, -0.41776815,
        -1.10325546,  0.60439732, -0.10558415],
       [-0.84488505, -0.99820778, -0.16054575,  0.15453319, -0.26510678,
        -0.49404308, -0.92076261, -1.04154944],
       [-1.14185152,  0.5040552 , -1.50468724,  0.90726993,  0.5304233 ,
         1.4097456 ,  5.4849091 , -0.0204964 ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=6)
print("train : ", X_train, y_train)
print("test : " , X_test, y_test)

train :  [[-0.54791859 -0.68523633  0.04624525 ... -1.47132127 -0.71539454
  -0.53102292]
 [-0.84488505 -0.05929342  0.87340925 ...  1.72704372  1.01513346
  -0.36084741]
 [-0.84488505 -1.5615564   0.45982725 ...  0.15324507 -0.15063235
  -1.04154944]
 ...
 [ 1.53084665 -0.27837344  0.66661825 ... -0.48135115  2.44666971
   1.4259954 ]
 [-0.25095213  1.28648383 -0.88431425 ...  0.66092205  0.54399494
  -0.78628618]
 [-1.14185152  0.41016376 -0.57412775 ... -0.7098058  -0.36204066
  -1.04154944]] [0 1 0 1 1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 1
 1 0 0 1 0 0 1 1 0 0 0 1 1 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0
 1 1 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0
 1 0 1 1 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 1 0 0 0 1
 0 1 0 1 0 1 0 1 1 1 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1
 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 0 1 0 

In [ ]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)
lr


LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
yhat = lr.predict(X_test)
yhat

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1])

In [ ]:
from sklearn.metrics import jaccard_similarity_score, confusion_matrix,log_loss, classification_report
jaccard_similarity_score(y_test, yhat)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.7922077922077922

In [ ]:
print(classification_report(y_test,yhat))

              precision    recall  f1-score   support

           0       0.82      0.88      0.85       103
           1       0.72      0.61      0.66        51

    accuracy                           0.79       154
   macro avg       0.77      0.75      0.76       154
weighted avg       0.79      0.79      0.79       154



In [ ]:
confusion_matrix(y_test, yhat)

array([[91, 12],
       [20, 31]])

In [ ]:
yhatprob = lr.predict_proba(X_test)
yhatprob

array([[0.81015601, 0.18984399],
       [0.51711533, 0.48288467],
       [0.60242198, 0.39757802],
       [0.68760187, 0.31239813],
       [0.81410202, 0.18589798],
       [0.63185149, 0.36814851],
       [0.63605903, 0.36394097],
       [0.71782722, 0.28217278],
       [0.62366824, 0.37633176],
       [0.77231534, 0.22768466],
       [0.78608559, 0.21391441],
       [0.2931248 , 0.7068752 ],
       [0.48083879, 0.51916121],
       [0.27069621, 0.72930379],
       [0.8095101 , 0.1904899 ],
       [0.70876979, 0.29123021],
       [0.38977865, 0.61022135],
       [0.54879719, 0.45120281],
       [0.70683269, 0.29316731],
       [0.28606252, 0.71393748],
       [0.82759257, 0.17240743],
       [0.69022184, 0.30977816],
       [0.75130235, 0.24869765],
       [0.65459969, 0.34540031],
       [0.56600069, 0.43399931],
       [0.58234169, 0.41765831],
       [0.66087731, 0.33912269],
       [0.5776097 , 0.4223903 ],
       [0.60465941, 0.39534059],
       [0.67119796, 0.32880204],
       [0.

In [ ]:
log_loss(y_test,yhatprob)

0.5062754762083385